batch_size: 24
epochs: 80
past_length: 10
future_length: 10
log_interval: 1
test_interval: 1
lr: 5.e-4
epoch_decay: 5
lr_gamma: 0.9
nf: 80
channels: 32
time_exp: 0
weight_decay: 5.e-4
scale: 100
apply_decay: true
res_pred: false
mask_ratio: 0.5
encoder_depth: 4
decoder_depth: 1
decoder_dim: 80
mlp_dim: 64
dim_per_head: 16
same_head: false
range_mask_ratio: false
mlp_head: false
mask_past: true
mask_range: 10
multi_output: true
decoder_masking: false
pred_all: false
maskpred: false
denoise: true
noise_dev: 0.8
part_noise: true
denoise_mode: past
part_noise_ratio: 0.4
add_joint_token: true
concat_vel: true
weighted_loss: false
max_weight: 5
only_recons_past: false
add_residual: true 
regular_masking: false
multi_same_head: false
range_noise_dev: false

